package assignment;


//import java.io.BufferedReader;
//import java.io.FileReader;
//import java.io.File;
//import java.io.FileNotFoundException;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//import javax.swing.table.DefaultTableModel;
//import javax.swing.event.ListSelectionEvent;
//import javax.swing.event.ListSelectionListener;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ProjectManagerUI extends javax.swing.JFrame {
    /**
     * Creates new form MainFrame
     */
    private ProjectManager proj = new ProjectManager();
    private System system = new System();
    private String[] assessmentTypes = {"Internship", "Investigation Report", "CP1", "CP2", "RMCP", "FYP"};
    
    public ProjectManagerUI(String id, boolean isPM) {
        
        
        initComponents();
        /*
        if(proj.getRole().equals("Project Manager")){
            this.setVisible(true);
        }*/
        idLbl.setText(id);
        jLabel8.setText(proj.getUsername());
        proj.comboBoxType(AssessmentTypeComboBox);
        proj.setRole(changeRole, this, isPM);
        studentT.setDefaultEditor(Object.class, null);
        AssessmentTbl.setDefaultEditor(Object.class,null);
        lecturerT.setDefaultEditor(Object.class, null);
        statusT.setDefaultEditor(Object.class, null);
        system.setScaledImage("umaru.png", profileLbl);
        system.setScaledImage("back icon.png", backIcn);
        system.setScaledImage("refresh icon.png", refreshIcn);  
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        UpTab = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        logoutlbl = new javax.swing.JLabel();
        backIcn = new javax.swing.JLabel();
        refreshIcn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AllotButton = new javax.swing.JButton();
        AssignLButton = new javax.swing.JButton();
        ViewSButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        changeRole = new javax.swing.JComboBox<>();
        profileLbl = new javax.swing.JLabel();
        userRoleTxt = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        Blank = new javax.swing.JPanel();
        AllotStudent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCOURSE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AssessmentTypeComboBox = new javax.swing.JComboBox<>();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldNAME = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        AllotB = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        studentT = new javax.swing.JTable();
        showBtn = new javax.swing.JButton();
        AssignLecturer = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lecturerT = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        showStu = new javax.swing.JButton();
        showLec = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lecturerSupSec = new javax.swing.JComboBox<>();
        AssignLec = new javax.swing.JButton();
        jTextFieldID2 = new javax.swing.JTextField();
        jTextFieldName2 = new javax.swing.JTextField();
        jTextFieldAsseT2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        AssessmentTbl = new javax.swing.JTable();
        AssignLecToStu = new javax.swing.JButton();
        ViewStatus = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusT = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonStatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(255, 255, 255));

        UpTab.setBackground(new java.awt.Color(245, 245, 245));

        jLabel6.setText("Academic Guidance Hub ");

        logoutlbl.setForeground(new java.awt.Color(52, 152, 219));
        logoutlbl.setText("Log Out?");
        logoutlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutlblMouseClicked(evt);
            }
        });

        backIcn.setMaximumSize(new java.awt.Dimension(16, 16));
        backIcn.setMinimumSize(new java.awt.Dimension(16, 16));
        backIcn.setPreferredSize(new java.awt.Dimension(16, 16));
        backIcn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backIcnMouseClicked(evt);
            }
        });

        refreshIcn.setMaximumSize(new java.awt.Dimension(16, 16));
        refreshIcn.setMinimumSize(new java.awt.Dimension(16, 16));
        refreshIcn.setPreferredSize(new java.awt.Dimension(16, 16));
        refreshIcn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshIcnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UpTabLayout = new javax.swing.GroupLayout(UpTab);
        UpTab.setLayout(UpTabLayout);
        UpTabLayout.setHorizontalGroup(
            UpTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpTabLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backIcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshIcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(422, 422, 422)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutlbl)
                .addGap(25, 25, 25))
        );
        UpTabLayout.setVerticalGroup(
            UpTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backIcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(refreshIcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(logoutlbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("USERNAME");

        AllotButton.setBackground(new java.awt.Color(255, 255, 255));
        AllotButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AllotButton.setForeground(new java.awt.Color(51, 51, 51));
        AllotButton.setText("Allot Student");
        AllotButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AllotButton.setContentAreaFilled(false);
        AllotButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AllotButton.setMaximumSize(new java.awt.Dimension(88, 18));
        AllotButton.setMinimumSize(new java.awt.Dimension(88, 18));
        AllotButton.setPreferredSize(new java.awt.Dimension(88, 18));
        AllotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllotButtonActionPerformed(evt);
            }
        });

        AssignLButton.setBackground(new java.awt.Color(255, 255, 255));
        AssignLButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AssignLButton.setForeground(new java.awt.Color(51, 51, 51));
        AssignLButton.setText("Assign Lecturer");
        AssignLButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AssignLButton.setContentAreaFilled(false);
        AssignLButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AssignLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignLButtonActionPerformed(evt);
            }
        });

        ViewSButton.setBackground(new java.awt.Color(255, 255, 255));
        ViewSButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ViewSButton.setForeground(new java.awt.Color(51, 51, 51));
        ViewSButton.setText("View Status");
        ViewSButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ViewSButton.setContentAreaFilled(false);
        ViewSButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewSButton.setMaximumSize(new java.awt.Dimension(88, 18));
        ViewSButton.setMinimumSize(new java.awt.Dimension(88, 18));
        ViewSButton.setPreferredSize(new java.awt.Dimension(88, 18));
        ViewSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewSButtonActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setOpaque(true);
        jLabel12.setPreferredSize(new java.awt.Dimension(88, 18));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setOpaque(true);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setOpaque(true);

        changeRole.setBackground(new java.awt.Color(255, 255, 255));
        changeRole.setOpaque(true);
        changeRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeRoleActionPerformed(evt);
            }
        });

        profileLbl.setText("user");

        userRoleTxt.setForeground(new java.awt.Color(102, 102, 102));
        userRoleTxt.setText("Project Manager");

        idLbl.setForeground(new java.awt.Color(102, 102, 102));
        idLbl.setText("id");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(headerLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(AssignLButton))
                            .addGroup(headerLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(headerLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(ViewSButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(headerLayout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(profileLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(headerLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(AllotButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(703, 703, 703))
                            .addGroup(headerLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(userRoleTxt)
                                    .addComponent(idLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(changeRole, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(UpTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addComponent(idLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                                .addComponent(changeRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(12, 12, 12)
                                .addComponent(userRoleTxt)
                                .addGap(7, 7, 7)))
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewSButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AllotButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AssignLButton))))
                    .addComponent(profileLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        body.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout BlankLayout = new javax.swing.GroupLayout(Blank);
        Blank.setLayout(BlankLayout);
        BlankLayout.setHorizontalGroup(
            BlankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
        );
        BlankLayout.setVerticalGroup(
            BlankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        body.add(Blank, "card3");

        AllotStudent.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ID       :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Allot :");

        jTextFieldCOURSE.setEditable(false);
        jTextFieldCOURSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCOURSEActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Name :");

        AssessmentTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssessmentTypeComboBoxActionPerformed(evt);
            }
        });

        jTextFieldID.setEditable(false);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jTextFieldNAME.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Allocate Student");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Course :");

        AllotB.setText("OK");
        AllotB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllotBActionPerformed(evt);
            }
        });

        studentT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Course", "Status"
            }
        ));
        studentT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(studentT);

        showBtn.setText("Show List");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AllotStudentLayout = new javax.swing.GroupLayout(AllotStudent);
        AllotStudent.setLayout(AllotStudentLayout);
        AllotStudentLayout.setHorizontalGroup(
            AllotStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllotStudentLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AllotStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(AllotStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AllotB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldID)
                    .addComponent(jTextFieldNAME)
                    .addComponent(jTextFieldCOURSE)
                    .addComponent(AssessmentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
            .addGroup(AllotStudentLayout.createSequentialGroup()
                .addGroup(AllotStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AllotStudentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AllotStudentLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(showBtn)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        AllotStudentLayout.setVerticalGroup(
            AllotStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllotStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(AllotStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AllotStudentLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(AllotStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AllotStudentLayout.createSequentialGroup()
                                .addGroup(AllotStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(AllotStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(40, 40, 40))
                            .addGroup(AllotStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jTextFieldCOURSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(AllotStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(AssessmentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(AllotB))
                    .addGroup(AllotStudentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(showBtn)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        body.add(AllotStudent, "card2");

        lecturerT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Department", "Role"
            }
        ));
        jScrollPane3.setViewportView(lecturerT);
        if (lecturerT.getColumnModel().getColumnCount() > 0) {
            lecturerT.getColumnModel().getColumn(0).setMinWidth(70);
            lecturerT.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        jLabel9.setText("Student");

        jLabel10.setText("Lecturer");

        showStu.setText("Show List");
        showStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStuActionPerformed(evt);
            }
        });

        showLec.setText("Show List");
        showLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLecActionPerformed(evt);
            }
        });

        jLabel15.setText("ID :");

        jLabel16.setText("Name :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Student Information");

        jLabel18.setText("Assessment Type :");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Assign Lecturer");

        jLabel23.setText("Role :");

        lecturerSupSec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supervisor", "Second Marker" }));
        lecturerSupSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerSupSecActionPerformed(evt);
            }
        });

        AssignLec.setText("Assign Role");
        AssignLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignLecActionPerformed(evt);
            }
        });

        jTextFieldID2.setEditable(false);
        jTextFieldID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldID2ActionPerformed(evt);
            }
        });

        jTextFieldName2.setEditable(false);

        jTextFieldAsseT2.setEditable(false);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Assign Lecturer");

        AssessmentTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Course", "Assessment"
            }
        ));
        AssessmentTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssessmentTblMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(AssessmentTbl);

        AssignLecToStu.setText("Assign Teacher");
        AssignLecToStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignLecToStuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AssignLecturerLayout = new javax.swing.GroupLayout(AssignLecturer);
        AssignLecturer.setLayout(AssignLecturerLayout);
        AssignLecturerLayout.setHorizontalGroup(
            AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssignLecturerLayout.createSequentialGroup()
                .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AssignLecturerLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssignLecturerLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(showStu))
                            .addGroup(AssignLecturerLayout.createSequentialGroup()
                                .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(AssignLecturerLayout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(jLabel21)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(155, 155, 155))
                    .addGroup(AssignLecturerLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(AssignLecturerLayout.createSequentialGroup()
                                .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel15))
                                .addGap(41, 41, 41)
                                .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldAsseT2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(jTextFieldID2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AssignLecturerLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel16))
                        .addGap(23, 23, 23)
                        .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lecturerSupSec, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldName2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AssignLec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AssignLecToStu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssignLecturerLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showLec))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssignLecturerLayout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel19)))))
                .addGap(487, 487, 487))
            .addGroup(AssignLecturerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AssignLecturerLayout.setVerticalGroup(
            AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssignLecturerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showStu)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(showLec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AssignLecturerLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel19)
                        .addGap(124, 124, 124)
                        .addComponent(jLabel20)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AssignLecturerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AssignLecturerLayout.createSequentialGroup()
                                .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel22))
                                .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AssignLecturerLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15))
                                        .addGap(18, 18, 18)
                                        .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel18)
                                            .addComponent(jTextFieldAsseT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssignLecturerLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lecturerSupSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldName2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16)))))
                            .addGroup(AssignLecturerLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(AssignLecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(AssignLecturerLayout.createSequentialGroup()
                                        .addComponent(AssignLec)
                                        .addGap(18, 18, 18)
                                        .addComponent(AssignLecToStu))
                                    .addGroup(AssignLecturerLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(43, 43, 43)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(97, 97, 97))))
        );

        body.add(AssignLecturer, "card4");

        statusT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Assessment", "Status"
            }
        ));
        jScrollPane1.setViewportView(statusT);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Project Status");

        jButtonStatus.setText("Show List");
        jButtonStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewStatusLayout = new javax.swing.GroupLayout(ViewStatus);
        ViewStatus.setLayout(ViewStatusLayout);
        ViewStatusLayout.setHorizontalGroup(
            ViewStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewStatusLayout.createSequentialGroup()
                .addGroup(ViewStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ViewStatusLayout.createSequentialGroup()
                        .addGroup(ViewStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewStatusLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel25))
                            .addGroup(ViewStatusLayout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 236, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(ViewStatusLayout.createSequentialGroup()
                .addGap(549, 549, 549)
                .addComponent(jButtonStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ViewStatusLayout.setVerticalGroup(
            ViewStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonStatus)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        body.add(ViewStatus, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 1195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSButtonActionPerformed
        jLabel12.setBackground(new Color(255,255,255));
        jLabel13.setBackground(new Color(255,255,255));
        jLabel14.setBackground(new Color(189,72,249));
        system.newPanel(body,ViewStatus);
    }//GEN-LAST:event_ViewSButtonActionPerformed

    private void logoutlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutlblMouseClicked
        this.dispose();
    }//GEN-LAST:event_logoutlblMouseClicked

    private void AllotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllotButtonActionPerformed
        jLabel12.setBackground(new Color(189,72,249));
        jLabel13.setBackground(new Color(255,255,255));
        jLabel14.setBackground(new Color(255,255,255));
        system.newPanel(body,AllotStudent);
    }//GEN-LAST:event_AllotButtonActionPerformed

    private void showStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStuActionPerformed
        String filePath = "StudentAssessment.txt";
        proj.showList1(filePath,AssessmentTbl);
    }//GEN-LAST:event_showStuActionPerformed

    private void showLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLecActionPerformed
        String filePath = "teacher.txt";
        proj.showLec(filePath, lecturerT);
    }//GEN-LAST:event_showLecActionPerformed

    private void AssignLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignLButtonActionPerformed
        jLabel12.setBackground(new Color(255,255,255));
        jLabel13.setBackground(new Color(189,72,249));
        jLabel14.setBackground(new Color(255,255,255));
        system.newPanel(body,AssignLecturer);
    }//GEN-LAST:event_AssignLButtonActionPerformed

    private void AssignLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignLecActionPerformed
        String filePath = "teacher.txt";
        proj.assignLec(filePath,lecturerT,lecturerSupSec);
    }//GEN-LAST:event_AssignLecActionPerformed

    private void jTextFieldID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldID2ActionPerformed

    private void lecturerSupSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerSupSecActionPerformed

    }//GEN-LAST:event_lecturerSupSecActionPerformed

    private void AssessmentTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssessmentTblMouseClicked
        proj.assessmentTMouseClicked(AssessmentTbl, jTextFieldID2, jTextFieldName2, jTextFieldAsseT2);
    }//GEN-LAST:event_AssessmentTblMouseClicked

    private void jButtonStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatusActionPerformed
        String filePath = "StudentAssessment.txt";
        proj.showStatus(filePath,statusT);
    }//GEN-LAST:event_jButtonStatusActionPerformed

    private void changeRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeRoleActionPerformed
        if(changeRole.getSelectedItem().equals("Lecturer")){
            this.dispose();
            LecturerUI LecturerMenu = new LecturerUI();
            LecturerMenu.setVisible(true);
        }        
    }//GEN-LAST:event_changeRoleActionPerformed

    private void backIcnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backIcnMouseClicked
        /*
        addUserLbl.setBackground(new Color(255,255,255));
        editDetailLbl.setBackground(new Color(255,255,255));
        editRoleLbl.setBackground(new Color(255,255,255));
        viewFeedbackLbl.setBackground(new Color(255,255,255));
        */
        system.newPanel(body, Blank);
    }//GEN-LAST:event_backIcnMouseClicked

    private void refreshIcnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshIcnMouseClicked
        system.refresh(body);
    }//GEN-LAST:event_refreshIcnMouseClicked

    private void studentTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTMouseClicked
        proj.studentTMouseClicked(studentT, jTextFieldID, jTextFieldNAME, jTextFieldCOURSE);
    }//GEN-LAST:event_studentTMouseClicked

    private void AllotBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllotBActionPerformed
        String filePath = "StudentAssessment.txt";
        proj.allotButtonActionPerformed(filePath,studentT,AssessmentTypeComboBox);
    }//GEN-LAST:event_AllotBActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void AssessmentTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssessmentTypeComboBoxActionPerformed

    }//GEN-LAST:event_AssessmentTypeComboBoxActionPerformed

    private void jTextFieldCOURSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCOURSEActionPerformed

    }//GEN-LAST:event_jTextFieldCOURSEActionPerformed

    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed
        String filepath = "StudentAssessment.txt";
        proj.showList(filepath, studentT);
    }//GEN-LAST:event_showBtnActionPerformed

    private void AssignLecToStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignLecToStuActionPerformed
        String filePath = "StudentAssessment.txt";     
        proj.assignlecTostudent(filePath,AssessmentTbl,lecturerT);// TODO add your handling code here:
    }//GEN-LAST:event_AssignLecToStuActionPerformed

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new ProjectManagerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllotB;
    private javax.swing.JButton AllotButton;
    private javax.swing.JPanel AllotStudent;
    private javax.swing.JTable AssessmentTbl;
    private javax.swing.JComboBox<String> AssessmentTypeComboBox;
    private javax.swing.JButton AssignLButton;
    private javax.swing.JButton AssignLec;
    private javax.swing.JButton AssignLecToStu;
    private javax.swing.JPanel AssignLecturer;
    private javax.swing.JPanel Blank;
    private javax.swing.JPanel UpTab;
    private javax.swing.JButton ViewSButton;
    private javax.swing.JPanel ViewStatus;
    private javax.swing.JLabel backIcn;
    private javax.swing.JPanel body;
    private javax.swing.JComboBox<String> changeRole;
    private javax.swing.JPanel header;
    private javax.swing.JLabel idLbl;
    private javax.swing.JButton jButtonStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldAsseT2;
    private javax.swing.JTextField jTextFieldCOURSE;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldID2;
    private javax.swing.JTextField jTextFieldNAME;
    private javax.swing.JTextField jTextFieldName2;
    private javax.swing.JComboBox<String> lecturerSupSec;
    private javax.swing.JTable lecturerT;
    private javax.swing.JLabel logoutlbl;
    private javax.swing.JLabel profileLbl;
    private javax.swing.JLabel refreshIcn;
    private javax.swing.JButton showBtn;
    private javax.swing.JButton showLec;
    private javax.swing.JButton showStu;
    private javax.swing.JTable statusT;
    private javax.swing.JTable studentT;
    private javax.swing.JLabel userRoleTxt;
    // End of variables declaration//GEN-END:variables
}
